### ISSUE TITLE
secondary camera

### ISSUE THREAD

**Issue by nickquednow** [maverick-boiler-robotics-team-4272/tuning2020#3]
was talking with Austin, and he would like camera on back of robot to make it easier to intake balls

**Comment by Bobobalink** [comment]
This should be really easy to do by plugging a USB camera we have into the limelight. You should research how it can stream a second camera feed to the website and we can show both (or maybe have an operator button to switch between them?)

**Comment by nickquednow** [comment]
Was looking at documentation and it does not consume too much bandwidth for the limelight and a video stream. They said something around 3.1Mbps at max
